# Generated by Django 5.2.6 on 2025-09-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BridesOfSaima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
