# Generated by Django 5.2.6 on 2025-09-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BridesOfSaima', '0003_invoice_advance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Bride's name", max_length=200)),
                ('location', models.CharField(help_text='Wedding/event location', max_length=200)),
                ('event_date', models.DateField(help_text='Date of the makeup/event')),
                ('tagline', models.CharField(help_text='Special tagline or description', max_length=300)),
                ('image', models.ImageField(help_text="Bride's photo after makeup", upload_to='brides/')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this bride on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bride',
                'verbose_name_plural': 'My Brides',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
