# Generated by Django 5.2.6 on 2025-09-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BridesOfSaima', '0004_bride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bride',
            name='image',
            field=models.ImageField(help_text='Main bride photo for gallery thumbnail', upload_to='brides/'),
        ),
        migrations.CreateModel(
            name='BrideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional bride photo', upload_to='brides/additional/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='BridesOfSaima.bride')),
            ],
            options={
                'verbose_name': 'Bride Image',
                'verbose_name_plural': 'Bride Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
